[build]
builder = "DOCKERFILE"
dockerfilePath = "server/Dockerfile"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/api/me"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
